# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  build-test:
    desc: Build the project and run tests 
    cmds:
      - cmake --build build
      - ./build/json_tests
    silent: true
