# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  
  build:
    desc: Build the project
    cmds:
      - cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja
      - cmake --build build
    silent: true

  test:
    deps: [build]
    desc: Build the project and run tests 
    cmds:
      - ./build/cpu_tests -d
    silent: true
